### ISSUE TITLE
Subaru long TODOs

### ISSUE THREAD

**Issue by jnewb1** [jnewb1/openpilot#51]
Preglobal

Global

Gen2

**Comment by Emalton** [comment]
On Pre-Global, looks like some signals need to be passed through
![20231104_215737](https://github.com/jnewb1/openpilot/assets/9328458/1246b843-7cb8-45aa-b702-bc5c634c1327)

**Comment by easher** [comment]
Mind clearifying what the bug is here? If these systems should be disabled then I feel like the lights make sense
